name: Create Fancy QR Code

on:
  workflow_dispatch:
    inputs:
      data:
        description: 'data to generate qr code'
        type: string
        required: true
      version:
        description: 'enter version of qr code'
        type: int
        required: true
      logo_image:
        description: 'enter file location of logo'
        type: string
        required: true
      img_location:
        description: 'enter file location of center image'
        type: string
        required: true

jobs:
  plan:
    runs-on: ubuntu-latest
    name: Create fancy qr-code
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DATA: ${{ inputs.data }}
      VERSION: ${{ inputs.version }}
      LOGO_IMAGE: ${{ inputs.logo_image }}
      IMG_LOCATION: ${{ inputs.img_location }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.9.5
        id: install_python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.5

      - name: Create Fancy QR
        id: create_fancy_qr_code
        run: |
          VIRTUAL_ENV="$(pwd)/.venv"
          mkdir -p $VIRTUAL_ENV
          python -m venv $VIRTUAL_ENV
          export PATH="$VIRTUAL_ENV/bin:$PATH"
          pip install -r requirements.txt
          python base_qr_model.py

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: final.png
          retention-days: 5