name: Lint Checks

on:
  push:
    branches:
      - "**"
      - "!master"

jobs:
  pants:
    name: Run Lint Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR Branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python 3.9.5
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.5
      - name: Install dependencies
        run: |
          pip install black
          pip install flake8
          pip install pylint
          pip install isort
      - name: Run Check
        run: |
          black .
          flake8
          find . -type f -name "*.py" | xargs pylint  #finds all files ending in .py and runs pylint on them
          isort .
      